config/routes.rb
Rails.application.routes.draw do
  post "/login", to: redirect("/auth/google_oauth2"), as: :login
  get "/auth/google_oauth2/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  post "/logout", to: "sessions#destroy", as: :logout

  resources :items, only: %i[index show] do
    scope module: :items do
      resources :rental_transactions, only: %i[new create]
      resource :conversation, only: %i[show] do
        scope module: :conversations do
          resources :messages, only: %i[create]
        end
      end
    end
  end

  namespace :user do
    resource :user_profile, only: %i[show new create edit update]
    resources :items, only: %i[index show new create edit update]
    resources :borrower_rental_transactions, only: %i[index show] do
      scope module: :borrower_rental_transactions do
        resource :review, only: %i[new create]
        resource :returned_rental, only: %i[create]
      end
    end
    resources :lender_rental_transactions, only: %i[index show] do
      scope module: :lender_rental_transactions do
        resource :rejected_rental, only: %i[create]
        resource :approved_rental, only: %i[create]
        resource :paid_rental, only: %i[create]
        resource :shipped_rental, only: %i[create]
        resource :completed_rental, only: %i[create]
        resource :review, only: %i[new create]
      end
    end
  end

  root "home#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_profile, dependent: :restrict_with_exception
  has_many :user_profile_versions, through: :user_profile, class_name: "UserProfileVersion"
  has_many :items, dependent: :restrict_with_exception
  has_many :lender_rental_transactions, class_name: "RentalTransaction", foreign_key: "lender_id", dependent: :restrict_with_exception
  has_many :borrower_rental_transactions, class_name: "RentalTransaction", foreign_key: "borrower_id", dependent: :restrict_with_exception
  has_many :messages, dependent: :restrict_with_exception

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :google_uid, presence: true, uniqueness: true

  delegate :address, :phone_number, :bank_account_info, to: :user_profile, allow_nil: true

  class << self
    def find_or_create_from_auth_hash(auth_hash)
      transaction do
        user =
          where(email: auth_hash[:info][:email], google_uid: auth_hash[:uid]).first_or_create! do |u|
            u.name = auth_hash[:info][:name]
          end
        user.create_user_profile!
      end
    end
  end
end

app/controllers/user/borrower_rental_transactions/base_controller.rb
class User::BorrowerRentalTransactions::BaseController < ApplicationController
  before_action :set_borrower_rental_transaction


  private

  def set_borrower_rental_transaction
    @borrower_rental_transaction = current_user.borrower_rental_transactions.find(params[:borrower_rental_transaction_id])
  end
end

app/controllers/user/borrower_rental_transactions/returned_rentals_controller.rb
class User::BorrowerRentalTransactions::ReturnedRentalsController < User::BorrowerRentalTransactions::BaseController
  def create
    @borrower_rental_transaction.create_returned_rental!
    redirect_to user_borrower_rental_transaction_url(@borrower_rental_transaction), notice: "貸出リクエストを返却済みにしました"
  end
end

app/controllers/user/borrower_rental_transactions/reviews_controller.rb
class User::BorrowerRentalTransactions::ReviewsController < User::BorrowerRentalTransactions::BaseController
  def new
    @review = @borrower_rental_transaction.reviews.build
  end

  def create
    @review = @borrower_rental_transaction.reviews.build(review_params)
    if @review.save
      redirect_to user_borrower_rental_transaction_url(@borrower_rental_transaction), notice: "レビューしました"
    else
      render :new, status: :unprocessable_content
    end
  end

  private

    def review_params
      params.expect(review: %i[rating comment]).merge(user_id: @borrower_rental_transaction.borrower.id)
    end
end

app/controllers/user/borrower_rental_transactions_controller.rb
class User::BorrowerRentalTransactionsController < ApplicationController
  before_action :set_borrower_rental_transaction, only: %i[show]

  def index
    @borrower_rental_transactions = current_user.borrower_rental_transactions.latest.page(params[:page])
  end

  def show
  end

  private

  def set_borrower_rental_transaction
    @borrower_rental_transaction = current_user.borrower_rental_transactions.find(params[:id])
  end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit]

  def index
    @items = current_user.items.latest.page(params[:page])
  end

  def show
  end

  def new
    @item = current_user.items.build
    @item.item_versions.build
  end

  def create
    @item = current_user.items.build(new_item_params)
    if @item.save
      redirect_to user_item_path(@item), notice: "アイテムを作成しました"
    else
      render :new, status: :unprocessable_content
    end
  end

  def edit
    @item_version = @item.build_from_current_item_version
  end

  def update
    @item = current_user.items.find(edit_item_params[:item_id])
    @item_version = @item.item_versions.build(edit_item_params)
    if @item_version.save
      redirect_to user_item_path(@item), notice: "アイテムを更新しました"
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

    def set_item
      @item = current_user.items.find(params[:id])
    end

    def new_item_params
      params.expect(item: { item_tag_ids: [], item_versions_attributes: [ %i[name description condition daily_price availability_status] ] })
    end

    def edit_item_params
      params.expect(item_version: %i[item_id name description condition daily_price availability_status])
    end
end

app/controllers/user/lender_rental_transactions/approved_rentals_controller.rb
class User::LenderRentalTransactions::ApprovedRentalsController < User::LenderRentalTransactions::BaseController
  def create
    @lender_rental_transaction.create_approved_rental!
    redirect_to user_lender_rental_transaction_url(@lender_rental_transaction), notice: "貸出リクエストを承認しました"
  end
end

app/controllers/user/lender_rental_transactions/base_controller.rb
class User::LenderRentalTransactions::BaseController < ApplicationController
  before_action :set_lender_rental_transaction


  private

  def set_lender_rental_transaction
    @lender_rental_transaction = current_user.lender_rental_transactions.find(params[:lender_rental_transaction_id])
  end
end

app/controllers/user/lender_rental_transactions/completed_rentals_controller.rb
class User::LenderRentalTransactions::CompletedRentalsController < User::LenderRentalTransactions::BaseController
  def create
    @lender_rental_transaction.create_completed_rental!
    redirect_to user_lender_rental_transaction_url(@lender_rental_transaction), notice: "貸出リクエストを完了済みにしました"
  end
end

app/controllers/user/lender_rental_transactions/paid_rentals_controller.rb
class User::LenderRentalTransactions::PaidRentalsController < User::LenderRentalTransactions::BaseController
  def create
    @lender_rental_transaction.create_paid_rental!
    redirect_to user_lender_rental_transaction_url(@lender_rental_transaction), notice: "貸出リクエストを支払い済みにしました"
  end
end

app/controllers/user/lender_rental_transactions/rejected_rentals_controller.rb
class User::LenderRentalTransactions::RejectedRentalsController < User::LenderRentalTransactions::BaseController
  def create
    @lender_rental_transaction.create_rejected_rental!
    redirect_to user_lender_rental_transaction_url(@lender_rental_transaction), notice: "貸出リクエストを拒否しました"
  end
end

app/controllers/user/lender_rental_transactions/reviews_controller.rb
class User::LenderRentalTransactions::ReviewsController < User::LenderRentalTransactions::BaseController
  def new
    @review = @lender_rental_transaction.reviews.build
  end

  def create
    @review = @lender_rental_transaction.reviews.build(review_params)
    if @review.save
      redirect_to user_lender_rental_transaction_url(@lender_rental_transaction), notice: "レビューしました"
    else
      render :new, status: :unprocessable_content
    end
  end

  private

  def review_params
    params.expect(review: %i[rating comment]).merge(user_id: @lender_rental_transaction.lender.id)
  end
end

app/controllers/user/lender_rental_transactions/shipped_rentals_controller.rb
class User::LenderRentalTransactions::ShippedRentalsController < User::LenderRentalTransactions::BaseController
  def create
    @lender_rental_transaction.create_shipped_rental!
    redirect_to user_lender_rental_transaction_url(@lender_rental_transaction), notice: "貸出リクエストを発送済みにしました"
  end
end

app/controllers/user/lender_rental_transactions_controller.rb
class User::LenderRentalTransactionsController < ApplicationController
  before_action :set_lender_rental_transaction, only: %i[show]

  def index
    @lender_rental_transactions = current_user.lender_rental_transactions.latest.page(params[:page])
  end

  def show
  end

  private

    def set_lender_rental_transaction
      @lender_rental_transaction = current_user.lender_rental_transactions.find(params[:id])
    end
end

app/controllers/user/user_profiles_controller.rb
class User::UserProfilesController < ApplicationController
  before_action :set_user_profile
  before_action :redirect_if_no_user_profile_versions, only: %i[show edit update]

  def show
  end

  def new
    @user_profile_version = @user_profile.user_profile_versions.build
  end

  def create
    @user_profile_version = @user_profile.user_profile_versions.build(user_profile_version_params)
    if @user_profile_version.save
      redirect_to user_user_profile_path, notice: "ユーザープロフィールを作成しました"
    else
      render :new, status: :unprocessable_content
    end
  end

  def edit
    @user_profile_version = @user_profile.build_user_profile_version_from_current_version
  end

  def update
    @user_profile_version = @user_profile.user_profile_versions.build(user_profile_version_params)
    if @user_profile_version.save
      redirect_to user_user_profile_path, notice: "ユーザープロフィールを更新しました"
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

    def set_user_profile
      @user_profile = current_user.user_profile
    end

    def user_profile_version_params
      params.expect(user_profile_version: %i[address phone_number bank_account_info])
    end

    def redirect_if_no_user_profile_versions
      unless @user_profile.user_profile_versions.exists?
        redirect_to new_user_profile_path, notice: "ユーザープロフィールを作成してください"
      end
    end
end

app/views/user/lender_rental_transactions/index.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    %h1.fs-2.text-center.my-4 貸出アイテム一覧
    %ul.list-group
      - @lender_rental_transactions.each do |lender_rental_transaction|
        %li.list-group-item
          = link_to lender_rental_transaction.item_version.name, user_lender_rental_transaction_path(lender_rental_transaction)
    .mt-2
      = paginate @lender_rental_transactions

app/views/user/lender_rental_transactions/show.html.haml
.row.justify-content-center.align-items-center
  .col-md-8.col-11
    - item_version = @lender_rental_transaction.item_version
    %h1.fs-2.text-center.my-4 #{item_version.name}の貸出
    .d-flex.justify-content-between.align-items-center
      - case @lender_rental_transaction.status
      - when :requested
        = button_to '貸出リクエストを承認する', user_lender_rental_transaction_approved_rental_path(@lender_rental_transaction),
          data: { turbo_confirm: "本当に承認しますか？" }, class: 'btn btn-primary'
        = button_to '貸出リクエストを拒否する', user_lender_rental_transaction_rejected_rental_path(@lender_rental_transaction),
        data: { turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger'
      - when :approved
        = button_to '入金済み', user_lender_rental_transaction_paid_rental_path(@lender_rental_transaction),
          data: { turbo_confirm: "本当に入金済みにしますか？" }, class: 'btn btn-primary'
      - when :paid
        = button_to '配送済み', user_lender_rental_transaction_shipped_rental_path(@lender_rental_transaction),
          data: { turbo_confirm: "本当に配送済みにしますか？" }, class: 'btn btn-primary'
      - when :returned
        = button_to '完了済み', user_lender_rental_transaction_completed_rental_path(@lender_rental_transaction),
          data: { turbo_confirm: "本当に完了済みにしますか？" }, class: 'btn btn-primary'

      - if %i[returned completed].include?(@lender_rental_transaction.status) && @lender_rental_transaction.lender_review.blank?
        = link_to 'レビューを書く', new_user_lender_rental_transaction_review_path(@lender_rental_transaction), class: 'btn btn-primary'
    .vstack.gap-3
      - %i[borrower_name status starts_on ends_on price].each do |attribute|
        %hr
        .row
          .col-3
            %h6.mb-0= RentalTransaction.human_attribute_name(attribute)
          .col-9
            - case attribute
            - when :status
              .vstack.gap-2
                %p.mb-0= rental_transaction_status_label(rental_transaction: @lender_rental_transaction)
                - case @lender_rental_transaction.status
                - when :approved
                  %p.mb-0
                    下記の銀行口座に借り手からの入金があれば、入金済みボタンを教えてください。
                    %br
                    = @lender_rental_transaction.borrower.bank_account_info
                - when :paid
                  %p.mb-0 下記のQRコードを梱包資材に貼り付けて、配送してください。
                  = qrcode_tag(@lender_rental_transaction.borrower_qr_code.payload.to_s, module_size: 3)
            - else
              = @lender_rental_transaction.public_send(attribute)
      - %i[description condition daily_price].each do |attribute|
        %hr
        .row
          .col-3
            %h6.mb-0= ItemVersion.human_attribute_name(attribute)
          .col-9
            = item_version.public_send(attribute)
      - if @lender_rental_transaction.lender_review.present?
        %hr
        .row
          .col-3
            %h6.mb-0 レビュー評価
          .col-9
            = @lender_rental_transaction.lender_review.rating
        %hr
        .row
          .col-3
            %h6.mb-0 レビューコメント
          .col-9
            = @lender_rental_transaction.lender_review.comment
      %hr