config/routes.rb
Rails.application.routes.draw do
  post "/login", to: redirect("/auth/google_oauth2"), as: :login
  get "/auth/google_oauth2/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  post "/logout", to: "sessions#destroy", as: :logout

  resources :items, only: %i[index show] do
    scope module: :items do
      resources :rental_transactions, only: %i[new create]
      resource :conversation, only: %i[show] do
        scope module: :conversations do
          resources :messages, only: %i[create]
        end
      end
    end
  end

  namespace :user do
    resource :user_profile, only: %i[show new create edit update]
    resources :items, only: %i[index show new create edit update]
    resources :borrower_rental_transactions, only: %i[index show] do
      scope module: :borrower_rental_transactions do
        resource :review, only: %i[new create]
        resource :returned_rental, only: %i[create]
      end
    end
    resources :lender_rental_transactions, only: %i[index show] do
      scope module: :lender_rental_transactions do
        resource :rejected_rental, only: %i[create]
        resource :approved_rental, only: %i[create]
        resource :paid_rental, only: %i[create]
        resource :shipped_rental, only: %i[create]
        resource :completed_rental, only: %i[create]
        resource :review, only: %i[new create]
      end
    end
  end

  root "home#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_flash.html.haml
.toast-container.position-fixed.top-0.end-0.pt-5.pe-2
  - flash.each do |key, value|
    .toast{ data: { controller: :toast }, role: :alert }
      .toast-body{ class: "d-flex justify-content-between align-items-center text-white bg-#{key == "notice" ? "success" : "danger"}" }
        %p.mb-0= value
        %button.btn-close{ type: :button, data: { bs: { dismiss: :toast } }, aria: { label: "閉じる" } }

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.shadow.sticky-top.bg-dark
  .container-fluid
    = link_to "CollectiShare", root_path, class: "navbar-brand"
    %button.navbar-toggler{ type: :button, data: { bs: { toggle: :collapse, target: "#navbar-nav" } }, aria: { controls: "navbar-nav", expanded: false } }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-nav
      %ul.navbar-nav
        - if current_user.present?
          %li.nav-item
            = link_to "アイテム", items_path, class: "nav-link"
          %li.nav-item
            = link_to "マイページ", user_user_profile_path, class: "nav-link"
          %li.nav-item
            = link_to "マイアイテム", user_items_path, class: "nav-link"
          %li.nav-item
            = link_to "借入アイテム", user_borrower_rental_transactions_path, class: "nav-link"
          %li.nav-item
            = link_to "貸出アイテム", user_lender_rental_transactions_path, class: "nav-link"
          %li.nav-item
            = button_to 'ログアウト', logout_path, method: :post, data: { turbo: false }, class: 'btn btn-danger'
        - else
          %li.nav-item
            = button_to 'ログイン', login_path, method: :post, data: { turbo: false }, class: 'btn btn-info'

app/views/layouts/_rails-template-inspector.html.haml
%script{ src: "https://cdn.skypack.dev/@aki77/rails-template-inspector@^0.5.0", type: "module" }
%rails-inspector{ "combo-key": "command-shift-v", root: "#{Rails.root}", "url-prefix": "x-mine://open?file=" }

app/views/layouts/application.html.haml
!!!
%html{ lang: "ja", data: { bs: { theme: :dark } } }
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Collecti Share"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}/
    %meta{content: "yes", name: "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "/icon.png", rel: "icon", type: "image/png"}/
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}/
    %link{href: "/icon.png", rel: "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    = debugbar_head if defined? Debugbar
  %body
    = render "layouts/flash"
    = render 'layouts/nav'
    = yield
    - if Rails.env.local?
      = render "layouts/rails-template-inspector"
    = debugbar_body cable: { url: "wss://localhost:3000/_debugbar/cable" } if defined? Debugbar